import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Providers from '@/components/rq/providers'
import Head from 'next/head'
import { PharmaciesProvider } from '../contexts/pharmaciesContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    return (
        <html lang="en">

            <Head>
                <link
                    rel="stylesheet"
                    type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
                />
                <link
                    rel="stylesheet"
                    type="text/css"
                    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
                />
            </Head>
            <body className={inter.className}>
                <Providers>
                    <PharmaciesProvider>
                        {children}
                    </PharmaciesProvider>
                </Providers>
            </body>
        </html>
    )
}
